show_welcome_message: true
messages:
  welcome: "§eThe Job of the Day is §a%jotd_current_job% §ewith a §a%jotd_current_boost%% §eboost."
  current: "§eThe Job of the Day is §a%jotd_current_job% §ewith a §a%jotd_current_boost%% §eboost."
  previous: "§eThe previous Job of the Day was §a%jotd_previous_job% §ewith a §a%jotd_previous_boost%% §eboost."
possible_boosts:
  exp: true
  money: true
  points: true
boosts_amounts:
  min: 10
  max: 50
excluded_jobs:
  -